desenvWebI/desenvWebI/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from appWeb.views import *
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', login_required(logout), {'next_page': reverse_lazy('index')}, name='logout'),
    url(r'^$', IndexListView.as_view(), name='index'),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # ----------------- CADASTROS -----------------
    url(r'^aluno/search$', AlunoOcorrenciaListView.as_view(), name='filtra_aluno'),
    url(r'^ocorrencia/add$', OcorrenciaCreateView.as_view(), name='cadastra_ocorrencia'),
    url(r'^ocorrencia/add/(?P<pk>\d+)/$', OcorrenciaCreateView.as_view(), name='cadastra_aluno_ocorrencia'),
    url(r'^tipo_permissao/add$', TipoOcorrenciaCreateView.as_view(), name='cadastra_tipo_ocorrencia'),
    url(r'^tipo_oferta/add$', TipoOfertaCreateView.as_view(), name='cadastra_tipo_oferta'),
    url(r'^tipo_func/add$', TipoFuncionarioCreateView.as_view(), name='cadastro_tipo_funcinario'),
    url(r'^aluno/add$', AlunoCreateView.as_view(), name='cadastra_aluno'),
    url(r'^funcionario/add$', FuncionarioCreateView.as_view(), name='cadastra_funcionario'),
    url(r'^turma/add$', TurmaCreateView.as_view(), name='cadastra_turma'),
    url(r'^curso/add$', CursoCreateView.as_view(), name='cadastra_curso'),

    # ----------------- EDIÇÃO -----------------
    url(r'^permissao/edit/(?P<pk>\d+)/$', OcorrenciaUpdateView.as_view(), name='edita_ocorrencia'),
    url(r'^aluno/edit/(?P<pk>\d+)/$', AlunoUpdateView.as_view(), name='edita_aluno'),
    url(r'^funcionario/edit/(?P<pk>\d+)/$', FuncionarioUpdateView.as_view(), name='edita_funcionario'),
    url(r'^turma/edit/(?P<pk>\d+)/$', TurmaUpdateView.as_view(), name='edita_turma'),
    url(r'^curso/edit/(?P<pk>\d+)/$', CursoUpdateView.as_view(), name='edita_curso'),

    # ----------------- REMOÇÃO -----------------
    url(r'^aluno/delete/(?P<pk>\d+)/$', AlunoDeleteView.as_view(), name='exclui_aluno'),
    url(r'^funcionario/delete/(?P<pk>\d+)/$', FuncionarioDeleteView.as_view(), name='exclui_funcionario'),
    url(r'^turma/delete/(?P<pk>\d+)/$', TurmaDeleteView.as_view(), name='exclui_turma'),
    url(r'^curso/delete/(?P<pk>\d+)/$', CursoDeleteView.as_view(), name='exclui_curso'),

    # ----------------- LISTAGEM -----------------
    url(r'^lista/funcionario/$', FuncionarioListView.as_view(), name='funcionario_list'),
    url(r'^lista/turma/$', TurmaListView.as_view(), name='turma_list'),
    url(r'^lista/curso/$', CursoListView.as_view(), name='curso_list'),
    url(r'^lista/aluno/$', AlunoListView.as_view(), name='aluno_list'),
    url(r'^lista/permissao/$', OcorrenciaListView.as_view(), name='ocorrencia_list'),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

desenvWebI/appWeb/models/aluno_model.py
# -*- coding: utf-8 -*-
from django.db import models

from appWeb.models.turma_model import TurmaModel
from appWeb.models.curso_model import CursoModel


class AlunoModel(models.Model):
    nome = models.CharField(max_length=80)
    email = models.EmailField(max_length=50)
    matricula = models.CharField(max_length=20)
    turma = models.ForeignKey(TurmaModel)
    curso = models.ForeignKey(CursoModel)
    nome_pai = models.CharField(max_length=80, blank=True, null=True)
    nome_mae = models.CharField(max_length=80)
    telefone_responsavel = models.CharField(max_length=9)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'

desenvWebI/appWeb/models/curso_model.py
# -*- coding: utf-8 -*-
from django.db import models

from appWeb.models.funcionario_model import FuncionarioModel
from appWeb.models.tipo_oferta_model import TipoOfertaModel


class CursoModel(models.Model):
    nome = models.CharField(max_length=80)
    descricao = models.TextField(max_length=200)
    duracao = models.CharField(max_length=2)
    oferta = models.ForeignKey(TipoOfertaModel, null=True, blank=True, related_name='_oferta_',
                              verbose_name='Oferta')
    coordenador = models.ForeignKey(FuncionarioModel, null=True, blank=True, related_name='_coordenador_',
                                    verbose_name='Coordenador')
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

desenvWebI/appWeb/models/funcionario_model.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from appWeb.models.tipo_funcionario_model import TipoFuncionarioModel


class FuncionarioModel(User):
    matricula = models.CharField(max_length=20)
    funcao = models.ForeignKey(TipoFuncionarioModel, verbose_name='Função')
    excluido = models.BooleanField(default=False)
    coordenador = models.BooleanField(default=False)

    def __unicode__(self):
        return self.first_name

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Funcionario'
        verbose_name_plural = 'Funcionários'

desenvWebI/appWeb/models/ocorrencia_model.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now

from appWeb.models.aluno_model import AlunoModel
from appWeb.models.funcionario_model import FuncionarioModel
from appWeb.models.tipo_ocorrencia_model import TipoOcorrenciaModel


class OcorrenciaModel(models.Model):
    aluno = models.ForeignKey(AlunoModel)
    tipo_ocorrencia = models.ForeignKey(TipoOcorrenciaModel)
    data_ocorrencia = models.DateField(default=now)
    hora_ocorrencia = models.TimeField(default=now)
    motivo = models.TextField(max_length=150)
    funcionario = models.ForeignKey(FuncionarioModel, null=True)
    excluido = models.BooleanField(default=False)


    def __unicode__(self):
        return self.aluno

    def __str__(self):
        return self.aluno

    class Meta:
        verbose_name = 'Ocorrência'
        verbose_name_plural = 'Ocorrências'

desenvWebI/appWeb/models/tipo_funcionario_model.py
# -*- coding: utf-8 -*-
from django.db import models

class TipoFuncionarioModel(models.Model):
    descricao = models.CharField(max_length=50)

    def __unicode__(self):
        return self.descricao

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = 'Tipo Funcionario'
        verbose_name_plural = 'Tipo Funcionários'

desenvWebI/appWeb/models/tipo_ocorrencia_model.py
# -*- coding: utf-8 -*-
from django.db import models

class TipoOcorrenciaModel(models.Model):
    nome = models.CharField(max_length=80)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        app_label = 'appWeb'
        verbose_name = 'Tipo Ocorrência'
        verbose_name_plural = 'Tipo Ocorrência'

desenvWebI/appWeb/models/tipo_oferta_model.py
from django.db import models


class TipoOfertaModel(models.Model):
    nome = models.CharField(max_length=50)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Tipo Oferta'
        verbose_name_plural = 'Tipo Ofertas'

desenvWebI/appWeb/models/turma_model.py
# -*- coding: utf-8 -*-
from django.db import models
from appWeb.models.curso_model import CursoModel


class TurmaModel(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(max_length=100)
    ano = models.CharField(max_length=30)
    curso = models.ForeignKey(CursoModel, related_name='_curso_',
                              verbose_name='Curso')
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        app_label = 'appWeb'
        verbose_name = 'Turma'
        verbose_name_plural = 'Turmas'

desenvWebI/appWeb/forms/aluno_form.py
# coding: utf-8
from django import forms
from appWeb.models.aluno_model import AlunoModel
from appWeb.models.turma_model import TurmaModel
from appWeb.models.curso_model import CursoModel



class AlunoForm(forms.ModelForm):
    turma = forms.ModelChoiceField(queryset=TurmaModel.objects.all().exclude(excluido=True))
    curso = forms.ModelChoiceField(queryset=CursoModel.objects.all().exclude(excluido=True))

    class Meta:
        model = AlunoModel
        exclude = ['excluido']

desenvWebI/appWeb/forms/curso_form.py
# coding: utf-8
from django import forms
from appWeb.models.curso_model import CursoModel
from appWeb.models.funcionario_model import FuncionarioModel
from appWeb.models.tipo_oferta_model import TipoOfertaModel


class CursoForm(forms.ModelForm):
    oferta = forms.ModelChoiceField(queryset=TipoOfertaModel.objects.all().exclude(excluido=True))
    coordenador= forms.ModelChoiceField(queryset=FuncionarioModel.objects.filter(funcao__nome__exact='Professor').exclude(excluido=True))

    class Meta:
        model = CursoModel
        exclude = ['excluido']
        widgets = {
            'descricao': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }

desenvWebI/appWeb/forms/funcionario_form.py
# coding: utf-8
from django import forms
from django.contrib.auth.hashers import make_password
from appWeb.models import TipoFuncionarioModel
from appWeb.models.funcionario_model import FuncionarioModel


class FuncionarioForm(forms.ModelForm):
    funcao = forms.ModelChoiceField(queryset=TipoFuncionarioModel.objects.all().exclude(excluido=True))

    class Meta:
        model = FuncionarioModel
        fields = ('first_name',
                  'last_name',
                  'email',
                  'username',
                  'password',
                  'matricula',
                  'funcao',
                  'coordenador',)
        exclude = ['excluido']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def save(self, commit=True):
        instance = super(FuncionarioForm, self).save(commit=False)
        instance.password = make_password(self.cleaned_data['password'])
        if commit:
            instance.save()
        return instance

desenvWebI/appWeb/forms/ocorrencia_form.py
# coding: utf-8
from django import forms
from appWeb.models.ocorrencia_model import OcorrenciaModel
from appWeb.models.aluno_model import AlunoModel


class OcorrenciaForm(forms.ModelForm):
    aluno = forms.ModelChoiceField(queryset=AlunoModel.objects.all().exclude(excluido=True))

    class Meta:
        model = OcorrenciaModel
        exclude = ['excluido', 'funcionario']
        widgets = {
            'motivo': forms.Textarea(attrs={'cols': 80, 'rows': 4}),
        }


TYPE_CHOICES = (
    ('nome', 'Nome'),
    ('matricula', 'Matricula'),
    ('turma', 'Turma'),
    ('curso', 'Curso'),
)


class AlunoSearchForm(forms.Form):
    name = forms.CharField()
    tipo = forms.Select(choices=TYPE_CHOICES)

desenvWebI/appWeb/forms/tipo_funcionario_form.py
# coding: utf-8
from django import forms
from appWeb.models.tipo_funcionario_model import TipoFuncionarioModel


class TipoFuncionarioForm(forms.ModelForm):

    class Meta:
        model = TipoFuncionarioModel
        fields = '__all__'
        exclude = ['excluido']

desenvWebI/appWeb/forms/tipo_ocorrencia_form.py
# coding: utf-8
from django import forms
from appWeb.models.tipo_ocorrencia_model import TipoOcorrenciaModel


class TipoOcorrenciaForm(forms.ModelForm):

    class Meta:
        model = TipoOcorrenciaModel
        exclude = ['excluido']

desenvWebI/appWeb/forms/tipo_oferta_form.py
# coding: utf-8
from django import forms
from appWeb.models.tipo_oferta_model import TipoOfertaModel


class TipoOfertaForm(forms.ModelForm):

    class Meta:
        model = TipoOfertaModel
        exclude = ['excluido']

desenvWebI/appWeb/forms/turma_form.py
# coding: utf-8
from django import forms
from appWeb.models.turma_model import TurmaModel


class TurmaForm(forms.ModelForm):

    class Meta:
        model = TurmaModel
        exclude = ['excluido']
        widgets = {
            'descricao': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }

desenvWebI/appWeb/views/aluno_view.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import *

from appWeb.forms.aluno_form import AlunoForm
from appWeb.models.aluno_model import AlunoModel


@method_decorator(login_required, name='dispatch')
class AlunoListView(ListView):
    queryset = AlunoModel.objects.filter(excluido=False).order_by('-id').distinct()
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class AlunoCreateView(CreateView):
    model = AlunoModel
    form_class = AlunoForm
    success_url = '/'


@method_decorator(login_required, name='dispatch')
class AlunoUpdateView(UpdateView):
    model = AlunoModel
    form_class = AlunoForm
    success_url = '/'


@method_decorator(login_required, name='dispatch')
class AlunoDeleteView(DeleteView):
    model = AlunoModel
    success_url = reverse_lazy('aluno_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.excluido = True
        self.object.save()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

desenvWebI/appWeb/views/appweb_view.py
# coding: utf-8
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from appWeb.models import OcorrenciaModel



@method_decorator(login_required, name='dispatch')
class IndexListView(ListView):
    queryset = OcorrenciaModel.objects.filter(excluido=False).order_by('-id').distinct()
    paginate_by = 10
    template_name = 'index.html'

desenvWebI/appWeb/views/curso_view.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import *

from appWeb.forms import CursoForm
from appWeb.models import CursoModel



@method_decorator(login_required, name='dispatch')
class CursoListView(ListView):
    queryset = CursoModel.objects.filter(excluido=False).order_by('-id').distinct()
    paginate_by = 10



@method_decorator(login_required, name='dispatch')
class CursoCreateView(CreateView):
    model = CursoModel
    form_class = CursoForm
    success_url = '/'


@method_decorator(login_required, name='dispatch')
class CursoUpdateView(UpdateView):
    model = CursoModel
    form_class = CursoForm
    success_url = '/'



@method_decorator(login_required, name='dispatch')
class CursoDeleteView(DeleteView):
    model = CursoModel
    success_url = reverse_lazy('curso_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.excluido = True
        self.object.save()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

desenvWebI/appWeb/views/funcionario_view.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import *
from appWeb.forms import FuncionarioForm
from appWeb.models.funcionario_model import FuncionarioModel


@method_decorator(login_required, name='dispatch')
class FuncionarioListView(ListView):
    queryset = FuncionarioModel.objects.filter(excluido=False).order_by('-id').distinct()
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class FuncionarioCreateView(CreateView):
    model = FuncionarioModel
    form_class = FuncionarioForm
    success_url = '/'


@method_decorator(login_required, name='dispatch')
class FuncionarioUpdateView(UpdateView):
    model = FuncionarioModel
    form_class = FuncionarioForm
    success_url = '/'


@method_decorator(login_required, name='dispatch')
class FuncionarioDeleteView(DeleteView):
    model = FuncionarioModel
    success_url = reverse_lazy('funcionario_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.excluido = True
        self.object.is_active = False
        self.object.save()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

desenvWebI/templates/appWeb/alunomodel_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block conteudo %}
    <form class="ui twelve wide column large form segment" action="" method="post">
        <h4 class="ui dividing header"><i class="users icon"></i>{%trans "Aluno" %}</h4>
        {% csrf_token %}
        <div class="ui equal width form">
            <div class="fields">
                <div class="field">
                    <label>{% trans "Nome" %}</label>
                    {{ form.nome }}
                    {% if form.nome.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.nome.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>E-mail</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="fields">
                <div class="field">
                    <label>{% trans "Turma" %}</label>
                    {{ form.turma }}
                    {% if form.turma.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.turma.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>{% trans "Curso" %}</label>
                    {{ form.curso }}
                    {% if form.curso.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.curso.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>{% trans "Número de Matrícula" %}</label>
                    {{ form.matricula }}
                    {% if form.matricula.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.matricula.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="three fields">
                <div class="field">
                    <label>{% trans "Nome da Mãe" %}</label>
                    {{ form.nome_mae }}
                    {% if form.nome_mae.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.nome_mae.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>{% trans "Nome do Pai" %}</label>
                    {{ form.nome_pai }}
                    {% if form.nome_pai.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.nome_pai.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>{% trans "Telefone do Responsável" %}</label>
                    {{ form.telefone_responsavel }}
                    {% if form.telefone_responsavel.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.telefone_responsavel.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
{#        {{ form.as_p }}#}
        {% include 'buttons.html' %}
    </form>

{% endblock %}

desenvWebI/templates/appWeb/alunomodel_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block conteudo %}
    <div class="ui twelve wide column segment">
        <h3 class="ui dividing header centered "><i class="student icon"></i>{% trans "Alunos" %}</h3>
        <div class="ui grid">
            <div class="two wide column"></div>
            <div class="two wide column"></div>

            <table class="ui compact  table">
                <thead class="full-width center aligned">
                <tr>
                    <th><i class="user icon"></i>{% trans "Pessoa" %}</th>
                    <th><i class="mail icon"></i>E-mail</th>
                    <th><i class="id card icon"></i>{% trans "Matrícula" %}</th>
                    <th><i class="settings icon"></i>{% trans "Ações" %}</th>
                </tr>
                </thead>
                <tbody class="center aligned">
                {% for aluno in object_list %}
                    <tr>
                        <td>{{ aluno.nome }}</td>
                        <td>{{ aluno.email }}</td>
                        <td>{{ aluno.matricula }}</td>
                        <td>
                            <div class="floated content">
                                <a class="ui left attached button blue" href="{% url 'edita_aluno' aluno.id %}">
                                    <i class="edit icon"></i>
                                </a>
                                <a class="right attached ui button red" href="{% url 'exclui_aluno' aluno.id %}">
                                    <i class="close icon "></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot class="full-width">
                <tr>
                    <th></th>
                    <th colspan="4">
                        <a class="ui right floated small green labeled icon button"
                           href="{% url 'cadastra_aluno' %}">
                            <i class="plus icon"></i> {% trans "Novo Aluno" %}
                        </a>
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

desenvWebI/templates/appWeb/ocorrenciamodel_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static tags_funcionario %}

{% block conteudo %}
    <form class="ui twelve wide column large form segment" action='' method="post">
        <h4 class="ui dividing header"><i class="announcement icon"></i>{% trans "Ocorrência" %}</h4>
        {% csrf_token %}
        <div class="ui equal width form">
            <div class="two fields">
                <div class="field">
                    <label>{% trans "Aluno" %}</label>
                    {% with request.get_full_path|get_aluno as aluno %}
                        {% if  aluno %}
                            <select id="id_aluno" name="aluno" class="ui disabled">
                                <option selected value="{{ aluno.id }}">{{ aluno.nome }}</option>
                            </select>
                        {% else %}
                            {{ form.aluno }}

                        {% endif %}
                    {% endwith %}
                    {% if form.aluno.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.aluno.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label>{% trans "Tipo de Ocorrência" %}</label>
                    {{ form.tipo_ocorrencia }}
                    {% if form.tipo_ocorrencia.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.tipo_ocorrencia.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="three fields">
                <div class="field">
                    <label>{% trans "Data" %}</label>
                    {{ form.data_ocorrencia }}
                </div>
                <div class="field">
                    <label>{% trans "Hora" %}</label>
                    {{ form.hora_ocorrencia }}
                </div>
                <div class="field">
                    <label>{% trans "Motivo" %}</label>
                    {{ form.motivo }}
                    {% if form.motivo.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.motivo.errors }}
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
        {#                {{ form.as_p }}#}
        {% include 'buttons.html' %}
    </form>
{% endblock %}

desenvWebI/templates/appWeb/search_alunomodel_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block conteudo %}
<div class="ui twelve wide column segment">
    <h3 class="ui dividing header centered "><i class="student icon"></i>{% trans "Ocorrência" %}</h3>
    <p class="ui teal message ">{% trans "Pesquise e selecione um aluno para adicionar uma ocorrência." %}</p>
    <form class="ui form" method="get" action="">
        {% csrf_token %}
            <div class="ui fields">
                <div class="ten wide field">
                    <p class="ui icon input">
                        <input name="name" class="" placeholder={% trans "Pesquisar por ..." %} type="text">
                        <i class="search icon"></i>
                    </p>
                </div>
                <p class="four wide field">
                    <select id="id_tipo" name="tipo">
                        <option value="nome">{% trans "Nome" %}</option>
                        <option value="matricula">{% trans "Matrícula" %}</option>
                        <option value="turma">{% trans "Turma" %}</option>
                        <option value="curso">{% trans "Curso" %}</option>
                    </select>
                </p>
                <p class="two wide field">
                    <button class="ui button" type="submit">{%trans "Pesquisar" %}</button>
                </p>
            </div>
    </form>

    <table class="ui compact  table">
        <thead class="full-width center aligned">
        <tr>
            <th><i class="user icon"></i>{% trans "Pessoa" %}</th>
            <th><i class="mail icon"></i> E-mail</th>
            <th><i class="id card icon"></i>{% trans "Número de matrícula" %}</th>
            <th><i class="add icon"></i>{% trans "Adicionar" %}</th>
        </tr>
        </thead>
        <tbody class="center aligned">
        {% for aluno in object_list %}
        <tr>
            <td>{{ aluno.nome }}</td>
            <td>{{ aluno.email }}</td>
            <td>{{ aluno.matricula }}</td>
            <td>
                <div class="floated content">
                    <a class="ui icon button blue" href="{% url 'cadastra_aluno_ocorrencia' aluno.id %}">
                        <i class="add icon"></i>
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot class="full-width">
        <tr>
            <th></th>
            <th colspan="4">
                <a class="ui right floated small green labeled icon button"
                   href="{% url 'cadastra_aluno' %}">
                    <i class="plus icon"></i> {% trans "Novo Aluno" %}
                </a>
            </th>
        </tr>
        </tfoot>
    </table>
</div>
</div>
{% endblock %}

desenvWebI/templates/appWeb/tipofuncionariomodel_form.html
{% extends 'base.html' %}ionario
{% load i18n %}
{% load static %}

{% block conteudo %}
        <form class="ui twelve wide column large form segment" action='' method="post">
            <h4 class="ui dividing header"><i class="users icon"></i>{% trans "Cadastro de Tipo de Funcionários" %}</h4>
            <div class="ui equal width form">
                <div class="three fields">
                    <div class="field"></div>
                    <div class="field">
                        <label>{% trans "Nome" %}</label>
                        {{ form.descricao }}
                        {% if form.descricao.errors %}
                            <div class="ui pointing red basic label">
                                {{ form.descricao.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="field"></div>
                </div>
            </div>
            {% include 'buttons.html' %}
        </form>
{% endblock %}